-- 回滚：恢复 v2-v5 为 NOT NULL DEFAULT ''
ALTER TABLE casbin_rule ALTER COLUMN v2 SET DEFAULT '';
ALTER TABLE casbin_rule ALTER COLUMN v2 SET NOT NULL;
ALTER TABLE casbin_rule ALTER COLUMN v3 SET DEFAULT '';
ALTER TABLE casbin_rule ALTER COLUMN v3 SET NOT NULL;
ALTER TABLE casbin_rule ALTER COLUMN v4 SET DEFAULT '';
ALTER TABLE casbin_rule ALTER COLUMN v4 SET NOT NULL;
ALTER TABLE casbin_rule ALTER COLUMN v5 SET DEFAULT '';
ALTER TABLE casbin_rule ALTER COLUMN v5 SET NOT NULL;
UPDATE casbin_rule SET v2 = '' WHERE v2 IS NULL;
UPDATE casbin_rule SET v3 = '' WHERE v3 IS NULL;
UPDATE casbin_rule SET v4 = '' WHERE v4 IS NULL;
UPDATE casbin_rule SET v5 = '' WHERE v5 IS NULL;
