// Code generated by Wire. DO NOT EDIT.
//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	appcasbin "github.com/tracerbiubiubiu/zhuzhao/internal/casbin"
	"github.com/tracerbiubiubiu/zhuzhao/internal/config"
	"github.com/tracerbiubiubiu/zhuzhao/internal/handler"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/jwt"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/logger"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/postgres"
	pgredis "github.com/tracerbiubiubiu/zhuzhao/internal/pkg/redis"
	"github.com/tracerbiubiubiu/zhuzhao/internal/repository"
	"github.com/tracerbiubiubiu/zhuzhao/internal/router"
	"github.com/tracerbiubiubiu/zhuzhao/internal/service"
)

// InitializeApp Wire 生成的注入代码
// TODO: 后续安装 wire CLI 后用 `wire` 命令自动生成替换此文件
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	// 基础设施
	log := logger.New(cfg.Log)
	jwtManager := jwt.NewManager(cfg.JWT)

	db, err := postgres.New(cfg.Database)
	if err != nil {
		return nil, nil, err
	}

	rdb, err := pgredis.New(cfg.Redis)
	if err != nil {
		db.Close()
		return nil, nil, err
	}

	enforcer, err := appcasbin.New(cfg.Casbin)
	if err != nil {
		db.Close()
		rdb.Close()
		return nil, nil, err
	}

	// Repository
	userRepo := repository.NewUserRepo(db)
	roleRepo := repository.NewRoleRepo(db)
	orgRepo := repository.NewOrgRepo(db)
	menuRepo := repository.NewMenuRepo(db)
	auditRepo := repository.NewAuditLogRepo(db)

	// Service
	authService := service.NewAuthService(userRepo, jwtManager, rdb)
	userService := service.NewUserService(userRepo)
	rbacService := service.NewRBACService(roleRepo)
	authzService := service.NewAuthzService(db, rdb)
	orgService := service.NewOrgService(orgRepo)
	menuService := service.NewMenuService(menuRepo)
	auditService := service.NewAuditService(auditRepo)
	_ = authzService
	_ = auditService

	// Handler
	authHandler := handler.NewAuthHandler(authService)
	userHandler := handler.NewUserHandler(userService, menuService)
	roleHandler := handler.NewRoleHandler(rbacService)
	orgHandler := handler.NewOrgHandler(orgService)
	menuHandler := handler.NewMenuHandler(menuService)

	// Router
	engine := router.New(router.Deps{
		AuthHandler: authHandler,
		UserHandler: userHandler,
		RoleHandler: roleHandler,
		OrgHandler:  orgHandler,
		MenuHandler: menuHandler,

		JWTManager:  jwtManager,
		Enforcer:    enforcer,
		RedisClient: rdb,
		Logger:      log,
	})

	// App
	application := NewApp(cfg, log, engine)

	// cleanup 按初始化的逆序关闭资源
	cleanup := func() {
		// TODO: 刷空审计日志队列
		enforcer.StopAutoLoadPolicy()
		_ = enforcer.SavePolicy()
		rdb.Close()
		db.Close()
		log.Info("resources cleaned up")
	}

	return application, cleanup, nil
}
