// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/tracerbiubiubiu/zhuzhao/internal/casbin"
	"github.com/tracerbiubiubiu/zhuzhao/internal/config"
	"github.com/tracerbiubiubiu/zhuzhao/internal/handler"
	"github.com/tracerbiubiubiu/zhuzhao/internal/middleware"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/jwt"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/logger"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/postgres"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/redis"
	"github.com/tracerbiubiubiu/zhuzhao/internal/pkg/resource"
	"github.com/tracerbiubiubiu/zhuzhao/internal/repository"
	"github.com/tracerbiubiubiu/zhuzhao/internal/router"
	"github.com/tracerbiubiubiu/zhuzhao/internal/service"
)

// Injectors from wire.go:

// InitializeApp Wire 注入入口
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	logConfig := cfg.Log
	slogLogger := logger.New(logConfig)
	databaseConfig := cfg.Database
	pool, cleanup, err := postgres.New(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repository.NewUserRepo(pool)
	jwtConfig := cfg.JWT
	manager := jwt.NewManager(jwtConfig)
	redisConfig := cfg.Redis
	client, cleanup2, err := redis.New(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	scripts := redis.NewScripts(client)
	auditLogRepo := repository.NewAuditLogRepo(pool)
	auditService := service.NewAuditService(auditLogRepo, userRepo)
	authService := service.NewAuthService(userRepo, manager, client, scripts, auditService, jwtConfig)
	authHandler := handler.NewAuthHandler(authService)
	roleRepo := repository.NewRoleRepo(pool)
	orgRepo := repository.NewOrgRepo(pool)
	orgService := service.NewOrgService(orgRepo, userRepo)
	userService := service.NewUserService(pool, userRepo, roleRepo, orgService, client, manager)
	menuRepo := repository.NewMenuRepo(pool)
	menuService := service.NewMenuService(menuRepo, userRepo, roleRepo)
	userHandler := handler.NewUserHandler(userService, menuService)
	casbinConfig := cfg.Casbin
	syncedEnforcer, cleanup3, err := casbin.New(casbinConfig, pool)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rbacService := service.NewRBACService(roleRepo, userRepo, menuRepo, syncedEnforcer)
	roleHandler := handler.NewRoleHandler(rbacService)
	orgHandler := handler.NewOrgHandler(orgService)
	menuHandler := handler.NewMenuHandler(menuService)
	auditHandler := handler.NewAuditHandler(auditService)
	deps := router.Deps{
		AuthHandler:  authHandler,
		UserHandler:  userHandler,
		RoleHandler:  roleHandler,
		OrgHandler:   orgHandler,
		MenuHandler:  menuHandler,
		AuditHandler: auditHandler,
		JWTManager:   manager,
		Enforcer:     syncedEnforcer,
		RedisClient:  client,
		DBPool:       pool,
		Logger:       slogLogger,
		RoleFetcher:  rbacService,
		AuditService: auditService,

		// B1-4：信任代理网段（空 = 不信任任何代理）
		TrustedProxies: cfg.Server.TrustedProxies,
	}
	engine := router.New(deps)
	app := NewApp(cfg, slogLogger, engine)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var pkgSet = wire.NewSet(logger.New, jwt.NewManager, postgres.New, redis.New, redis.NewScripts, resource.NewRegistry, casbin.New)

var repoSet = wire.NewSet(repository.NewUserRepo, repository.NewRoleRepo, repository.NewOrgRepo, repository.NewMenuRepo, repository.NewAuditLogRepo)

var serviceSet = wire.NewSet(service.NewAuthService, service.NewUserService, service.NewRBACService, service.NewAuthzService, service.NewOrgService, service.NewMenuService, service.NewAuditService, wire.Bind(new(middleware.RoleFetcher), new(*service.RBACService)), wire.Bind(new(middleware.AuditLogger), new(*service.AuditService)))

var handlerSet = wire.NewSet(handler.NewAuthHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewOrgHandler, handler.NewMenuHandler, handler.NewAuditHandler)
