// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"

	"github.com/google/wire"
	"github.com/tracerbiubiubiu/zhuzhao/internal/casbin"
	"github.com/tracerbiubiubiu/zhuzhao/internal/config"
	"github.com/tracerbiubiubiu/zhuzhao/internal/gateway"
	"github.com/tracerbiubiubiu/zhuzhao/internal/handler"
	"github.com/tracerbiubiubiu/zhuzhao/internal/middleware"
	"github.com/tracerbiubiubiu/zhuzhao/internal/repository"
	"github.com/tracerbiubiubiu/zhuzhao/internal/router"
	"github.com/tracerbiubiubiu/zhuzhao/internal/service"
	"github.com/tracerbiubiubiu/zhuzhao/internal/service/ticket"
)

// Injectors from wire.go:

// InitializeApp Wire 注入入口
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	logConfig := cfg.Log
	logger := provideLogger(logConfig)
	databaseConfig := cfg.Database
	pool, cleanup, err := providePostgres(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repository.NewUserRepo(pool)
	jwtConfig := cfg.JWT
	manager := provideJWTManager(jwtConfig)
	redisConfig := cfg.Redis
	client, cleanup2, err := provideRedis(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	scripts := provideRedisScripts(client)
	auditLogRepo := repository.NewAuditLogRepo(pool)
	auditService := service.NewAuditService(auditLogRepo, userRepo)
	authService := service.NewAuthService(userRepo, manager, client, scripts, auditService, jwtConfig)
	authHandler := handler.NewAuthHandler(authService)
	roleRepo := repository.NewRoleRepo(pool)
	orgRepo := repository.NewOrgRepo(pool)
	orgDelegationService := service.NewOrgDelegationService(pool)
	menuRepo := repository.NewMenuRepo(pool)
	casbinConfig := cfg.Casbin
	syncedEnforcer, cleanup3, err := casbin.New(casbinConfig, pool)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rbacService := service.NewRBACService(roleRepo, userRepo, menuRepo, syncedEnforcer)
	orgService := service.NewOrgService(orgRepo, userRepo, orgDelegationService, rbacService)
	userService := service.NewUserService(pool, userRepo, roleRepo, orgService, client, manager)
	menuService := service.NewMenuService(menuRepo, userRepo, roleRepo)
	userHandler := handler.NewUserHandler(userService, menuService)
	roleHandler := handler.NewRoleHandler(rbacService)
	orgHandler := handler.NewOrgHandler(orgService)
	menuHandler := handler.NewMenuHandler(menuService)
	auditHandler := handler.NewAuditHandler(auditService)
	ticketRepo := repository.NewTicketRepo(pool)
	jobSubmissionRepo := repository.NewJobSubmissionRepo(pool)
	taskrunnerConfig := cfg.Taskrunner
	taskrunnerClient := provideTaskrunnerClient(taskrunnerConfig)
	taskrunnerService := service.NewTaskrunnerService(taskrunnerClient, jobSubmissionRepo)
	taskrunnerHandler := provideTaskrunnerHandler(taskrunnerService, cfg.Taskrunner)
	policyEvalWriter := providePolicyEvalWriter(cfg.Audit, client, auditLogRepo, logger)
	registry := provideRegistry(policyEvalWriter)
	ticketService := ticket.NewTicketService(pool, ticketRepo, orgRepo, registry, rbacService, orgDelegationService)
	ticketHandler := handler.NewTicketHandler(ticketService)
	jobsRegistry := provideJobsRegistry(auditLogRepo, cfg.Audit, logger)
	jobsCallbackService := provideJobsCallbackService(jobsRegistry, jobSubmissionRepo, logger)
	jobsHandler := handler.NewJobsHandler(jobsCallbackService)
	v := provideTrustedProxies(cfg)
	// 批次 B/E13：网关反代注册表（gateway.upstreams 未配置时为 nil，不挂载）
	var gwRegistry *gateway.Registry
	if ups := cfg.Gateway.Upstreams; len(ups) > 0 {
		gwUps := make([]gateway.Upstream, len(ups))
		for i, u := range ups {
			gwUps[i] = gateway.Upstream{Prefix: u.Prefix, Target: u.Target, StripPrefix: u.StripPrefix}
		}
		gw, gwErr := gateway.New(gwUps, cfg.Gateway.AK, cfg.Gateway.SK)
		if gwErr != nil {
			return nil, nil, fmt.Errorf("gateway init: %w", gwErr)
		}
		gwRegistry = gw
	}
	deps := router.Deps{
		AuthHandler:       authHandler,
		UserHandler:       userHandler,
		RoleHandler:       roleHandler,
		OrgHandler:        orgHandler,
		MenuHandler:       menuHandler,
		AuditHandler:      auditHandler,
		TicketHandler:     ticketHandler,
		JobsHandler:       jobsHandler,
		TaskrunnerHandler: taskrunnerHandler,
		InternalJobs:      cfg.InternalJobs,
		Gateway:           gwRegistry,
		JWTManager:        manager,
		Enforcer:          syncedEnforcer,
		RedisClient:       client,
		DBPool:            pool,
		Logger:            logger,
		RoleFetcher:       rbacService,
		AuditService:      auditService,
		Registry:          registry,
		TrustedProxies:    v,
	}
	engine := router.New(deps)
	// BK-22 fail-fast：路由↔menu_apis 双向对账（缺口 = 拒绝启动，清单见错误信息；
	// 豁免集与网关前缀边界见 internal/router/catalog.go）
	prefixes := make([]string, 0, len(cfg.Gateway.Upstreams))
	for _, u := range cfg.Gateway.Upstreams {
		prefixes = append(prefixes, u.Prefix)
	}
	bound, boundErr := router.LoadBoundAPIs(context.Background(), pool)
	if boundErr != nil {
		return nil, nil, boundErr
	}
	if gaps := router.AuditRouteCatalog(engine.Routes(), bound, prefixes); len(gaps) > 0 {
		return nil, nil, fmt.Errorf("BK-22 路由↔menu_apis 对账失败（%d 项缺口，拒启 fail-fast）：%s",
			len(gaps), router.FormatGaps(gaps))
	}
	app := NewApp(cfg, logger, engine, policyEvalWriter)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var pkgSet = wire.NewSet(
	provideLogger,
	provideJWTManager,
	providePostgres,
	provideRedis,
	provideRedisScripts, providePolicyEvalWriter, provideRegistry, provideJobsRegistry, provideTaskrunnerClient, casbin.New,
)

var repoSet = wire.NewSet(repository.NewUserRepo, repository.NewRoleRepo, repository.NewOrgRepo, repository.NewMenuRepo, repository.NewAuditLogRepo, repository.NewTicketRepo, repository.NewJobSubmissionRepo)

var serviceSet = wire.NewSet(service.NewAuthService, service.NewUserService, service.NewRBACService, service.NewOrgDelegationService, service.NewOrgService, service.NewMenuService, service.NewAuditService, ticket.NewTicketService, wire.Bind(new(middleware.RoleFetcher), new(*service.RBACService)), wire.Bind(new(middleware.AuditLogger), new(*service.AuditService)), wire.Bind(new(ticket.OrgDelegationChecker), new(*service.OrgDelegationService)))

var handlerSet = wire.NewSet(handler.NewAuthHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewOrgHandler, handler.NewMenuHandler, handler.NewAuditHandler, handler.NewTicketHandler, handler.NewJobsHandler)

// provideTrustedProxies 信任代理网段（空 = 不信任任何代理，安全默认）
func provideTrustedProxies(cfg *config.Config) []string {
	return cfg.Server.TrustedProxies
}
