// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回 Token 对",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "description": "登出请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登出成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/password/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "修改密码请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "刷新 Token",
                "parameters": [
                    {
                        "description": "刷新请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/dead-letters": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "死信列表（运维向，配合 retry 端点闭环）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "任务定义列表（dept/action_id/enabled 过滤透传）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "新建任务定义（action_id + trigger_type + cron_spec + params）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "cron_spec 非法等",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/trigger": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "手动执行一次任务定义（「立即执行」按钮）",
                "responses": {
                    "200": {
                        "description": "task_id + accepted",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "409": {
                        "description": "定义已停用",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/jobs/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "修改任务定义（cron/params/启停；生效 ≤ 下个 cron tick）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orgs/members/role": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org"
                ],
                "summary": "任命/变更组内角色",
                "parameters": [
                    {
                        "description": "变更组内角色请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgMemberRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orgs/owners": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org"
                ],
                "summary": "设置组织负责人",
                "parameters": [
                    {
                        "description": "设置负责人请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgOwnersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orgs/roles/bind": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org"
                ],
                "summary": "组织绑定角色",
                "parameters": [
                    {
                        "description": "组织与角色",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orgs/roles/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org"
                ],
                "summary": "组织解绑角色",
                "parameters": [
                    {
                        "description": "组织与角色",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/orgs/roles/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "org"
                ],
                "summary": "组织已绑定角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "组织 ID",
                        "name": "org_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/runs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "query 透传：request_id / action / status / job_id / from / to（RFC3339）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "查执行记录（request_id 跨查即此）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "提交一次性任务（受理 ≠ 执行成功，结果经查询接口获取）",
                "parameters": [
                    {
                        "description": "提交参数（action 必填；callback_url 可缺省自动拼）",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_service.TaskSubmitInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "task_id + accepted",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "502": {
                        "description": "taskrunner 未配置/不可达",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "取消未开始的任务（执行中 409）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/retry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "重试失败/死信任务",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "执行结果的唯一出口；taskrunner 不主动推送",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "查任务状态（job_runs 全景 + live_state 实时态）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ticket-templates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单模板列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "新建工单模板",
                "parameters": [
                    {
                        "description": "模板定义",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ticket-templates/{code}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单模板详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模板编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "更新工单模板（patch；code/type/org 不可改）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模板编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "删除工单模板",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模板编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ticket-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单类型列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "新建工单类型",
                "parameters": [
                    {
                        "description": "类型定义",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ticket-types/admin": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "工单类型全量列表（含停用，管理端）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ticket-types/{code}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "更新工单类型（patch；code 不可改）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "类型编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "删除工单类型（有工单禁删 → 409）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "类型编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ticket-types/{code}/fields": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单类型字段定义",
                "parameters": [
                    {
                        "type": "string",
                        "description": "工单类型编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "全量替换类型字段集",
                "parameters": [
                    {
                        "type": "string",
                        "description": "类型编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "字段集",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.ReplaceTypeFieldsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/ticket-types/{code}/fields/admin": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket-admin"
                ],
                "summary": "类型字段读取（含 validate_regex，管理端）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "类型编码",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "工单类型",
                        "name": "type_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "工单状态",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "创建工单",
                "parameters": [
                    {
                        "description": "创建工单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/assign": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "分派工单",
                "parameters": [
                    {
                        "description": "分派工单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.AssignTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/close": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "关闭工单",
                "parameters": [
                    {
                        "description": "关闭工单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.CloseTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/comments": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "创建工单回复",
                "parameters": [
                    {
                        "description": "创建回复请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "删除工单",
                "parameters": [
                    {
                        "description": "删除工单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.DeleteTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/notes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "创建内部备注",
                "parameters": [
                    {
                        "description": "创建备注请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/relations": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "建立工单关联",
                "parameters": [
                    {
                        "description": "建立关联请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateRelationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "更新工单",
                "parameters": [
                    {
                        "description": "更新工单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工单 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/{id}/comments": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单回复列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工单 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/tickets/{id}/relations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ticket"
                ],
                "summary": "工单关联列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "工单 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/internal/jobs/callback": {
            "post": {
                "description": "结果映射（P6/P7）：2xx=执行完全成功/幂等受理；404=未知动作；409=不可重试；500=可重试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal-jobs"
                ],
                "summary": "预置动作回调（taskrunner → zhuzhao，AK/SK 验签内网端点）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.AssignTicketRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "assigned_to": {
                    "description": "nil = 取消分派",
                    "type": "string",
                    "example": "0"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.BindOrgRoleRequest": {
            "type": "object",
            "required": [
                "org_id",
                "role_id"
            ],
            "properties": {
                "org_id": {
                    "type": "string",
                    "example": "0"
                },
                "role_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CloseTicketRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "comment": {
                    "description": "可选关闭说明",
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateCommentRequest": {
            "type": "object",
            "required": [
                "content",
                "ticket_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "ticket_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateNoteRequest": {
            "type": "object",
            "required": [
                "content",
                "ticket_id"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "ticket_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateRelationRequest": {
            "type": "object",
            "required": [
                "source_ticket_id",
                "target_ticket_id"
            ],
            "properties": {
                "relation_type": {
                    "description": "默认 related",
                    "type": "string"
                },
                "source_ticket_id": {
                    "type": "string",
                    "example": "0"
                },
                "target_ticket_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketRequest": {
            "type": "object",
            "required": [
                "org_id",
                "title",
                "type_code"
            ],
            "properties": {
                "assigned_to": {
                    "type": "string",
                    "example": "0"
                },
                "custom_data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "description": {
                    "type": "string"
                },
                "org_id": {
                    "type": "string",
                    "example": "0"
                },
                "priority": {
                    "type": "integer"
                },
                "template_code": {
                    "description": "可选：命中模板则预填",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type_code": {
                    "type": "string"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTemplateRequest": {
            "type": "object",
            "required": [
                "code",
                "name",
                "org_id",
                "type_code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 50
                },
                "default_fields": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "default_priority": {
                    "type": "integer"
                },
                "default_sla_minutes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 200
                },
                "org_id": {
                    "type": "string",
                    "example": "0"
                },
                "type_code": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.CreateTicketTypeRequest": {
            "type": "object",
            "required": [
                "code",
                "name"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 50
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "states": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "transitions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.DeleteTicketRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.LoginRequest": {
            "type": "object",
            "required": [
                "employee_no",
                "password"
            ],
            "properties": {
                "device_id": {
                    "description": "D2-01：max=64——device_id 进 RT JWT claims 与 Redis 键（refresh:{uid}:{device}）",
                    "type": "string",
                    "maxLength": 64
                },
                "device_name": {
                    "type": "string",
                    "maxLength": 64
                },
                "employee_no": {
                    "description": "D2-01：max 对齐 DB varchar(50)——employee_no 直接进 Redis 锁定键\n（lock:login:{employee_no}），无上限时可灌入超大键撑爆 maxmemory 驱逐安全键",
                    "type": "string",
                    "maxLength": 50
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.LogoutRequest": {
            "type": "object",
            "properties": {
                "device_id": {
                    "description": "与登录时一致；空则使用 default",
                    "type": "string"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.ReplaceTypeFieldsRequest": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_tracerbiubiubiu_zhuzhao_internal_model.TicketTypeFieldInput"
                    }
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgMemberRoleRequest": {
            "type": "object",
            "required": [
                "org_id",
                "org_member_role",
                "user_id"
            ],
            "properties": {
                "org_id": {
                    "type": "string",
                    "example": "0"
                },
                "org_member_role": {
                    "type": "string",
                    "enum": [
                        "member",
                        "admin"
                    ]
                },
                "user_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.SetOrgOwnersRequest": {
            "type": "object",
            "required": [
                "org_id",
                "owner_user_ids"
            ],
            "properties": {
                "org_id": {
                    "type": "string",
                    "example": "0"
                },
                "owner_user_ids": {
                    "description": "元素为字符串 ID（项目惯例）；空数组=清空（仅全局）",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.TicketTypeFieldInput": {
            "type": "object",
            "required": [
                "field_key",
                "field_label",
                "field_type"
            ],
            "properties": {
                "field_key": {
                    "type": "string",
                    "maxLength": 50
                },
                "field_label": {
                    "type": "string",
                    "maxLength": 100
                },
                "field_options": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "field_type": {
                    "type": "string",
                    "enum": [
                        "input",
                        "textarea",
                        "number",
                        "date",
                        "select",
                        "multi_select",
                        "tips"
                    ]
                },
                "required": {
                    "type": "boolean"
                },
                "sort_order": {
                    "type": "integer"
                },
                "validate_regex": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdatePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "device_id": {
                    "description": "与登录时一致；空则使用 default",
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "priority": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTemplateRequest": {
            "type": "object",
            "properties": {
                "default_fields": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "default_priority": {
                    "type": "integer"
                },
                "default_sla_minutes": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_model.UpdateTicketTypeRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100
                },
                "states": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "transitions": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "github_com_tracerbiubiubiu_zhuzhao_internal_service.TaskSubmitInput": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "callback_url": {
                    "type": "string"
                },
                "dept": {
                    "description": "一次性任务归属标签（E-⑤ 组装用户可见标签；C11 快照列）",
                    "type": "string"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "task_id": {
                    "description": "可选：调用方幂等键",
                    "type": "string"
                },
                "timeout_secs": {
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
